spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/hausmeister_fix
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
server:
  port: 8088
  servlet:
   context-path:
springdoc:
  default-consumes-media-type: application/json

