services:
  postgres:
    container_name: postgres-hmfix
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    networks:
      - hmfix-net
  keycloak:
    container_name: keycloak-hmfix
    image: quay.io/keycloak/keycloak:26.2.1
    command:
      - "start-dev"
    environment:
     PROXY_ADDRESS_FORWARDING: "true"
     KC_HTTP_RELATIVE_PATH: /auth
     KC_HOSTNAME: localhost
     KC_HOSTNAME_PORT: "9090"
     KC_HOSTNAME_STRICT: "false"
     KC_BOOTSTRAP_ADMIN_USERNAME: admin
     KC_BOOTSTRAP_ADMIN_PASSWORD: admin
     KC_DB: postgres
     KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
     KC_DB_USERNAME: ${POSTGRES_USER:-username}
     KC_DB_PASSWORD: ${POSTGRES_PASSWORD:-password}
     KC_DB_SCHEMA: keycloak
    ports:
      - "9090:8080"
    depends_on:
      - postgres
    networks:
      - hmfix-net

volumes:
   postgres_data:
   keycloak_data:

networks:
  hmfix-net:
    driver: bridge